#!/usr/bin/env python3
"""
docker-entrypoint.sh (runs as Python)

Bridges TrueNAS Scale (or any orchestrator that passes env vars) into
the config.yml format the app expects.

Logic:
  1. If /config/config.yml already exists → use it as-is (user-managed).
  2. If UNIFI_HOST is set → generate config.yml from environment variables.
  3. Otherwise → crash with a helpful message.

This means the container works in two modes:
  - Standalone Docker: mount your own config.yml, nothing changes.
  - TrueNAS app: the catalog passes env vars via questions.yaml, this
    script turns them into config.yml on first boot.

Environment variables (all optional if config.yml exists):
  UNIFI_HOST, UNIFI_USERNAME, UNIFI_PASSWORD, UNIFI_TOKEN
  CAMERAS           — JSON array: [{"name":"...","rtsp_url":"..."},...]
  AI_MODEL, AI_DEVICE, AI_CONFIDENCE, AI_CONFIDENCE_PERSON,
  AI_CONFIDENCE_VEHICLE, AI_DETECT_PERSONS, AI_DETECT_VEHICLES,
  AI_FRAME_SKIP
  WEB_TOOL_ENABLED, WEB_TOOL_PORT
"""

import json
import os
import sys
from pathlib import Path

CONFIG_PATH = Path("/config/config.yml")


def generate_config():
    """Build config.yml from environment variables."""
    host = os.environ.get("UNIFI_HOST", "")
    username = os.environ.get("UNIFI_USERNAME", "")
    password = os.environ.get("UNIFI_PASSWORD", "")
    token = os.environ.get("UNIFI_TOKEN", "")

    cameras_json = os.environ.get("CAMERAS", "[]")
    try:
        cameras = json.loads(cameras_json)
    except json.JSONDecodeError:
        print(f"ERROR: CAMERAS env var is not valid JSON: {cameras_json!r}", file=sys.stderr)
        sys.exit(1)

    if not cameras:
        print("ERROR: No cameras configured. Set CAMERAS env var as a JSON array.", file=sys.stderr)
        print('  Example: CAMERAS=\'[{"name":"Front Door","rtsp_url":"rtsp://..."}]\'', file=sys.stderr)
        sys.exit(1)

    # AI settings (applied globally to all cameras from the form)
    ai_model = os.environ.get("AI_MODEL", "yolov8n.pt")
    ai_device = os.environ.get("AI_DEVICE", "auto")
    ai_confidence = float(os.environ.get("AI_CONFIDENCE", "0.50"))
    ai_confidence_person = float(os.environ.get("AI_CONFIDENCE_PERSON", "0.45"))
    ai_confidence_vehicle = float(os.environ.get("AI_CONFIDENCE_VEHICLE", "0.60"))
    ai_detect_persons = os.environ.get("AI_DETECT_PERSONS", "true").lower() == "true"
    ai_detect_vehicles = os.environ.get("AI_DETECT_VEHICLES", "true").lower() == "true"
    ai_frame_skip = int(os.environ.get("AI_FRAME_SKIP", "3"))

    # Web tool
    web_enabled = os.environ.get("WEB_TOOL_ENABLED", "true").lower() == "true"
    web_port = int(os.environ.get("WEB_TOOL_PORT", "8091"))

    # Build the YAML manually (no pyyaml dependency at entrypoint time —
    # keeps the logic self-contained and avoids import-order issues).
    lines = []
    lines.append("# Auto-generated by docker-entrypoint from environment variables.")
    lines.append("# Edit this file directly for advanced settings (lines, per-camera")
    lines.append("# overrides, etc.) — it won't be overwritten on restart.")
    lines.append("")
    lines.append("unifi:")
    lines.append(f"  host: {_quote(host)}")
    if token:
        lines.append(f"  token: {_quote(token)}")
    else:
        lines.append(f"  username: {_quote(username)}")
        lines.append(f"  password: {_quote(password)}")
    lines.append("")
    lines.append("web_tool:")
    lines.append(f"  enabled: {str(web_enabled).lower()}")
    lines.append(f"  port: {web_port}")
    lines.append("")
    lines.append("cameras:")

    for cam in cameras:
        name = cam.get("name", "Camera")
        rtsp_url = cam.get("rtsp_url", "")
        snapshot_url = cam.get("snapshot_url", "")

        lines.append(f"  - name: {_quote(name)}")
        lines.append(f"    rtsp_url: {_quote(rtsp_url)}")
        if snapshot_url:
            lines.append(f"    snapshot_url: {_quote(snapshot_url)}")
        lines.append("    ai:")
        lines.append(f"      model: {_quote(ai_model)}")
        lines.append(f"      device: {_quote(ai_device)}")
        lines.append(f"      confidence: {ai_confidence}")
        lines.append(f"      confidence_person: {ai_confidence_person}")
        lines.append(f"      confidence_vehicle: {ai_confidence_vehicle}")
        lines.append(f"      detect_persons: {str(ai_detect_persons).lower()}")
        lines.append(f"      detect_vehicles: {str(ai_detect_vehicles).lower()}")
        lines.append(f"      frame_skip: {ai_frame_skip}")
        lines.append("      # Use the web tool to add virtual lines:")
        lines.append(f"      # http://<truenas-ip>:{web_port}/")
        lines.append("      lines: []")
        lines.append("")

    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text("\n".join(lines) + "\n")
    print(f"Generated {CONFIG_PATH} from environment variables")


def _quote(val: str) -> str:
    """YAML-safe quoting for a string value."""
    if not val:
        return '""'
    # Quote anything that could be mis-parsed as YAML
    if any(c in val for c in ":#{}[]|>&*!%@`\"'\\,\n") or val.strip() != val:
        escaped = val.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return f'"{val}"'


def main():
    if CONFIG_PATH.exists():
        print(f"Using existing {CONFIG_PATH}")
    elif os.environ.get("UNIFI_HOST"):
        generate_config()
    else:
        print(
            f"ERROR: No {CONFIG_PATH} found and UNIFI_HOST not set.\n"
            "Either:\n"
            "  - Mount a config.yml at /config/config.yml, or\n"
            "  - Set UNIFI_HOST + CAMERAS environment variables\n"
            "    (TrueNAS app catalog does this automatically).",
            file=sys.stderr,
        )
        sys.exit(1)

    # Hand off to the real app
    config_arg = str(CONFIG_PATH)
    os.execvp(sys.executable, [sys.executable, "main.py", config_arg])


if __name__ == "__main__":
    main()
