#!/usr/bin/env python3
"""
docker-entrypoint.sh (runs as Python)

Bridges TrueNAS Scale (or any orchestrator that passes env vars) into
the config.yml format the app expects.

Logic:
  1. If /config/config.yml already exists -> use it as-is (user-managed).
  2. If UNIFI_HOST is set -> generate a minimal config.yml with just the
     controller connection + web tool enabled. Cameras and AI settings
     are added later through the web UI.
  3. Otherwise -> crash with a helpful message.

This means the container works in two modes:
  - Standalone Docker: mount your own config.yml, nothing changes.
  - TrueNAS app: the wizard passes host/creds, this script seeds
    config.yml, then the user adds cameras via the web UI.

Environment variables (all optional if config.yml exists):
  UNIFI_HOST, UNIFI_USERNAME, UNIFI_PASSWORD, UNIFI_TOKEN
  WEB_TOOL_PORT
"""

import os
import sys
from pathlib import Path

CONFIG_PATH = Path("/config/config.yml")


def generate_config():
    """Build a minimal config.yml from environment variables."""
    host = os.environ.get("UNIFI_HOST", "")
    username = os.environ.get("UNIFI_USERNAME", "")
    password = os.environ.get("UNIFI_PASSWORD", "")
    token = os.environ.get("UNIFI_TOKEN", "")
    web_port = int(os.environ.get("WEB_TOOL_PORT", "8091"))

    lines = []
    lines.append("# Auto-generated by docker-entrypoint.")
    lines.append("# Add cameras and AI settings via the web UI at")
    lines.append(f"# http://<host>:{web_port}/")
    lines.append("")
    lines.append("unifi:")
    lines.append(f"  host: {_quote(host)}")
    if token:
        lines.append(f"  token: {_quote(token)}")
    else:
        lines.append(f"  username: {_quote(username)}")
        lines.append(f"  password: {_quote(password)}")
    lines.append("")
    lines.append("web_tool:")
    lines.append("  enabled: true")
    lines.append(f"  port: {web_port}")
    lines.append("")
    lines.append("cameras: []")
    lines.append("")

    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text("\n".join(lines) + "\n")
    print(f"Generated {CONFIG_PATH} — open http://<host>:{web_port}/ to add cameras")


def _quote(val: str) -> str:
    """YAML-safe quoting for a string value."""
    if not val:
        return '""'
    if any(c in val for c in ":#{}[]|>&*!%@`\"'\\,\n") or val.strip() != val:
        escaped = val.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return f'"{val}"'


def main():
    if CONFIG_PATH.exists():
        print(f"Using existing {CONFIG_PATH}")
    elif os.environ.get("UNIFI_HOST"):
        generate_config()
    else:
        print(
            f"ERROR: No {CONFIG_PATH} found and UNIFI_HOST not set.\n"
            "Either:\n"
            "  - Mount a config.yml at /config/config.yml, or\n"
            "  - Set UNIFI_HOST environment variable\n"
            "    (TrueNAS app catalog does this automatically).",
            file=sys.stderr,
        )
        sys.exit(1)

    # Hand off to the real app
    config_arg = str(CONFIG_PATH)
    os.execvp(sys.executable, [sys.executable, "main.py", config_arg])


if __name__ == "__main__":
    main()
