#!/usr/bin/env python3
"""
docker-entrypoint.py (runs as Python)

Bridges TrueNAS Scale (or any orchestrator that passes env vars) into
the config.yml format the app expects.

Logic:
  1. If /config/config.yml already exists AND UNIFI_HOST is set ->
     update the unifi connection settings from env vars (so TrueNAS
     users can change host/creds without manually editing the file).
     Cameras and AI settings in the file are preserved.
  2. If /config/config.yml already exists and no UNIFI_HOST is set ->
     use it as-is (standalone Docker, user-managed).
  3. If no config.yml but UNIFI_HOST is set -> generate a minimal
     config.yml with just the controller connection + web tool enabled.
  4. Otherwise -> crash with a helpful message.

This means the container works in two modes:
  - Standalone Docker: mount your own config.yml, nothing changes.
  - TrueNAS app: the wizard passes host/creds, this script seeds
    config.yml, then the user adds cameras via the web UI.
    Changing env vars and restarting updates the config automatically.

Environment variables (all optional if config.yml exists):
  UNIFI_HOST, UNIFI_USERNAME, UNIFI_PASSWORD, UNIFI_TOKEN
  WEB_TOOL_PORT
"""

import os
import sys
from pathlib import Path

import yaml

CONFIG_PATH = Path("/config/config.yml")


def apply_env_overrides():
    """Update the unifi section of an existing config.yml from env vars.

    Only touches keys that have a corresponding env var set.
    Cameras, AI settings, web_tool, and everything else are preserved.
    """
    host = os.environ.get("UNIFI_HOST")
    if not host:
        return  # no env overrides requested

    try:
        with open(CONFIG_PATH) as f:
            cfg = yaml.safe_load(f) or {}
    except yaml.YAMLError as e:
        print(
            f"WARNING: {CONFIG_PATH} contains invalid YAML ({e}). "
            "Skipping env var overrides — fix the file or delete it to regenerate.",
            file=sys.stderr,
        )
        return

    unifi = cfg.setdefault("unifi", {})
    changed = False

    # Host — always apply when UNIFI_HOST is set
    if unifi.get("host") != host:
        unifi["host"] = host
        changed = True

    # Credentials — only update if the env var is actually set
    for env_key, cfg_key in [
        ("UNIFI_USERNAME", "username"),
        ("UNIFI_PASSWORD", "password"),
        ("UNIFI_TOKEN", "token"),
    ]:
        val = os.environ.get(env_key)
        if val and unifi.get(cfg_key) != val:
            unifi[cfg_key] = val
            changed = True

    # Web tool port
    web_port = os.environ.get("WEB_TOOL_PORT")
    if web_port:
        web_cfg = cfg.setdefault("web_tool", {})
        try:
            port_int = int(web_port)
            if web_cfg.get("port") != port_int:
                web_cfg["port"] = port_int
                changed = True
        except ValueError:
            print(
                f"WARNING: WEB_TOOL_PORT={web_port!r} is not a valid integer, ignoring.",
                file=sys.stderr,
            )

    if changed:
        try:
            CONFIG_PATH.write_text(yaml.dump(cfg, default_flow_style=False, sort_keys=False))
        except OSError as e:
            print(
                f"WARNING: Could not write updated config to {CONFIG_PATH}: {e}",
                file=sys.stderr,
            )
            return
        print(f"Updated {CONFIG_PATH} with environment variable overrides")
    else:
        print(f"Using existing {CONFIG_PATH} (env vars match)")


def generate_config():
    """Build a minimal config.yml from environment variables."""
    host = os.environ.get("UNIFI_HOST", "")
    username = os.environ.get("UNIFI_USERNAME", "")
    password = os.environ.get("UNIFI_PASSWORD", "")
    token = os.environ.get("UNIFI_TOKEN", "")
    web_port = int(os.environ.get("WEB_TOOL_PORT", "8091"))

    lines = []
    lines.append("# Auto-generated by docker-entrypoint.")
    lines.append("# Add cameras and AI settings via the web UI at")
    lines.append(f"# http://<host>:{web_port}/")
    lines.append("")
    lines.append("unifi:")
    lines.append(f"  host: {_quote(host)}")
    if token:
        lines.append(f"  token: {_quote(token)}")
    else:
        lines.append(f"  username: {_quote(username)}")
        lines.append(f"  password: {_quote(password)}")
    lines.append("")
    lines.append("web_tool:")
    lines.append("  enabled: true")
    lines.append(f"  port: {web_port}")
    lines.append("")
    lines.append("cameras: []")
    lines.append("")

    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text("\n".join(lines) + "\n")
    print(f"Generated {CONFIG_PATH} — open http://<host>:{web_port}/ to add cameras")


def _quote(val: str) -> str:
    """YAML-safe quoting for a string value."""
    if not val:
        return '""'
    if any(c in val for c in ":#{}[]|>&*!%@`\"'\\,\n") or val.strip() != val:
        escaped = val.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return f'"{val}"'


def main():
    if CONFIG_PATH.exists():
        apply_env_overrides()
    elif os.environ.get("UNIFI_HOST"):
        generate_config()
    else:
        print(
            f"ERROR: No {CONFIG_PATH} found and UNIFI_HOST not set.\n"
            "Either:\n"
            "  - Mount a config.yml at /config/config.yml, or\n"
            "  - Set UNIFI_HOST environment variable\n"
            "    (TrueNAS app catalog does this automatically).",
            file=sys.stderr,
        )
        sys.exit(1)

    # Hand off to the real app
    config_arg = str(CONFIG_PATH)
    os.execvp(sys.executable, [sys.executable, "main.py", config_arg])


if __name__ == "__main__":
    main()
